# Change these first
owner: xmanhwa
repo: uptime

sites:
  - name: xManhwa
    url: https://xmanhwa.net

status-website:
  cname: status.xmanhwa.net
  logoUrl: https://xmanhwa.net/favicon.ico
  favicon: https://xmanhwa.net/favicon.ico
  name: xManhwa Status
  introTitle: "**xManhwa System Status**"
  introMessage: This is the system status for the xManhwa service.
  navbar:
    - title: Home
      href: https://xmanhwa.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
